import 'dart:developer';
import 'dart:math' hide log;

import 'package:auto_route/auto_route.dart';
import 'package:delalty/core/common/components/widgets/build_carousel.dart';
import 'package:easy_localization/easy_localization.dart' hide TextDirection;
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/flutter_svg.dart';
import '../../../../app/functions.dart';
import '../../../../core/common/components/widgets/back_icon_widget.dart';
import '../../../../core/common/components/widgets/cached_image.dart';
import '../../../../core/common/components/widgets/centered_circular_progress_indicator.dart';
import '../../../../core/common/components/widgets/default_text_form_field.dart';
import '../../../../core/common/components/widgets/form_fields_icons/camera_icon.dart';
import '../../../../core/common/components/widgets/my_elevated_button.dart';
import '../../../../core/common/components/widgets/simple_text.dart';
import '../../../../core/common/components/widgets/simple_toast.dart';
import '../../../../core/common/components/widgets/user_image.dart';
import '../../../../core/resources/assets_manager.dart';
import '../../../../core/resources/colors_manager.dart';
import '../../../../core/resources/routes/app_router.dart';
import '../../../../core/resources/strings_manager.dart';
import '../../../../core/resources/text/styles_manager.dart';
import '../../../../core/services/socket/socket_cubit.dart';
import '../../../../data/requests/requests.dart';
import '../../../cubits/relationship_cubit/relationship_cubit.dart';
import '../../app/cubit/app_cubit.dart';
import '../cubit/conversation_cubit.dart';

part 'conversation_app_bar.dart';
part 'conversation_body.dart';
part 'conversation_container.dart';
part 'conversation_divider.dart';
part 'conversation_form_field.dart';
part 'conversation_messages_list.dart';
part 'conversation_more_button.dart';
part 'conversation_product_info.dart';
part 'conversation_reject_or_accept_contact.dart';
