part of 'widgets.dart';

class ProductDescripe extends StatelessWidget {
  const ProductDescripe({
    super.key,
  });

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        SimpleText(
          AppStrings.describe,
          textStyle: TextStyleEnum.poppinsMedium,
          fontSize: 15.sp,
        ),
        SizedBox(height: 18.h),
        SimpleText(
          'You can generate such text or many other texts in addition to increasing the number of letters generated by the application.',
          textStyle: TextStyleEnum.poppinsRegular,
          fontSize: 12.sp,
          color: AppColors.grey3,
        ),
      ],
    );
  }
}
